api_platform:
    title: Welcome to Woobile
    show_webby: false
    enable_swagger_ui: false
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    error_formats:
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
